AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ListS3Buckets:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::021172944394:role/service-role/ListS3Buckets-role-ntl888qr'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /ListS3Buckets
            Method: ANY
